### ISSUE TITLE
Endpoint for Metadata Only

### ISSUE THREAD

**Issue by ChristianGeng** [jschibberges/Bundestag-API#4]
# Problem

The `plenaryprotocol`  endpoints are designed to obtain plenary protocols containing the entire protocol including the full steno text extracted from the corresnporing pdfs. 

This is however not always what you want. 

Sometimes you only want to find the Wahlperiode, the document number or the title, but for the *entire* history of the parliament.  When getting all text, this might take a long time, and require more data transfer than really needed.

## Possible Solution

add secondary endpoints that do not retrieve the entire text but only metadata.

**Comment by jschibberges** [comment]
I added a "fulltext"-parameter to those functions searching or retrieving documents and plenary protocols. Default is false, because as you point out, this can lead to a lot of extra data transfered if not set intentionally.
