### ISSUE TITLE
New API key

### ISSUE THREAD

**Issue by hejjoe** [jschibberges/Bundestag-API#7]
https://github.com/jschibberges/Bundestag-API/blob/230c1ed72fc1d0174c9bb37a52df23a1170b417d/tests/test_btawrapper.py#L42

> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2025 gültige API-Key lautet:
> I9FKdCn.hbfefNWCY336dL6x62vfwNKpoN2RZ1gp21
> 
> Auf Anfrage können Sie auch einen eigenen API-Key mit einer Laufzeit von zunächst zehn Jahren erhalten. Ein eigener API-Key hat denselben Funktionsumfang wie der öffentliche API-Key.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: [parlamentsdokumentation@bundestag.de](mailto:parlamentsdokumentation@bundestag.de) 

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by jschibberges** [comment]
Danke für den Issue. Ist angepasst im Code. PIP-Package update folgt zeitnah.
